name: Autoversion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - 'release/v*.*'

concurrency:
  group: bump-version-${{ github.ref }}
  cancel-in-progress: false

jobs:
  bump:
    if: ${{ !github.event.repository.fork }}
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@48918a17e96079ba32d8379d536c89679ab39340 # v5.63.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.ACTIONS_GITHUB_TOKEN || github.token }}
      - uses: plengauer/autoversion@de18b86671e27145d689f84b43978cf5f1a5d16c # v5.2.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN || github.token }}
          increments: ${{ github.ref_name == 'main' && 'major;minor' || 'patch' }}
