name: Autoversion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - 'release/v*.*'

concurrency:
  group: bump-version-${{ github.ref }}
  cancel-in-progress: false

jobs:
  bump:
    if: ${{ !github.event.repository.fork }}
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@74b46584d99a285f5f5300264c94538dcf6e9596 # v5.62.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.ACTIONS_GITHUB_TOKEN || github.token }}
            ${{ secrets.OPENAI_TOKEN }}
      - uses: plengauer/autoversion@badee98ba4eb3a38f99cf8acab7f5510e7e8736f # v5.0.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN || github.token }}
          openai_token: ${{ secrets.OPENAI_TOKEN }}
          increments: ${{ github.ref_name == 'main' && 'major;minor' || 'patch' }}
