
name: OpenTelemetry
on:
  workflow_run:
    workflows:
      - .github/workflows/copilot-setup-steps.yml
      - Autoversion
      - CodeQL
      - Copilot
      - Copilot coding agent
      - Recompile Agentic Workflows
      - Renovate
      - Report Failed Workflows
    types:
      - completed
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/workflow@4804af0803d2753734b18fe4ef2a99b7e4ebdc07 # v5.42.1
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
    permissions:
      actions: read
