name: 'Deploy OpenTelemetry'

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-slim
    concurrency:
      group: deploy-otel-job-${{ github.ref_name }}
    permissions:
      contents: write
      pull-requests: write
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@2169fb0fa9a8260fde99a2a185bbf99a5d63546e # v5.59.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.ACTIONS_GITHUB_TOKEN }}
            ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
            ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
      - uses: plengauer/opentelemetry-github/actions/instrument/deploy@2169fb0fa9a8260fde99a2a185bbf99a5d63546e # v5.59.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
