
name: OpenTelemetry
on:
  workflow_run:
    workflows:
      - .github/workflows/copilot-setup-steps.yml
      - Autoversion
      - CodeQL
      - Copilot
      - Copilot coding agent
      - Recompile Agentic Workflows
      - Renovate
      - Report Failed Workflows
    types:
      - completed
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/workflow@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
    permissions:
      actions: read
