name: 'Deploy OpenTelemetry'

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-slim
    concurrency:
      group: deploy-otel-job-${{ github.ref_name }}
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.ACTIONS_GITHUB_TOKEN }}
            ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
            ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
      - uses: plengauer/opentelemetry-github/actions/instrument/deploy@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
    permissions:
      actions: read
