
name: OpenTelemetry
on:
  workflow_run:
    workflows:
      - .github/workflows/copilot-setup-steps.yml
      - Autobackport
      - Autoversion
      - Claude
      - CodeQL
      - Copilot
      - Copilot cloud agent
      - Copilot code review
      - OpenAI Codex
      - Recompile Agentic Workflows
      - Renovate
    types:
      - completed
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/workflow@db7b5a16bf2d905493c86f582aba4bb056d8aada # v5.62.1
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
    permissions:
      actions: read
