name: Renovate

on:
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@4804af0803d2753734b18fe4ef2a99b7e4ebdc07 # v5.42.1
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - uses: renovatebot/github-action@3633cede7d4d4598438e654eac4a695e46004420 # v46.1.7
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING_CONFIG_FILE_NAME: .github/renovate.json
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    permissions:
      actions: read
