name: Renovate

on:
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: write
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@db7b5a16bf2d905493c86f582aba4bb056d8aada # v5.62.1
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - uses: renovatebot/github-action@f3a31a786096ba6b40d0f0ffe11a494ef73bfa7c # v46.3.4
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING_CONFIG_FILE_NAME: .github/renovate.json
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
