name: Update Debian Repository

on:
  push:
    paths:
      - .github/workflows/update_debian_repository.yml

jobs:
  update-debian-repository:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: plengauer/create-debian-repository@2d3d79460d6c590c0f4e0dac6419d268c7d7a83d # v1.0.0
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
